# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


SOURCES += $$PWD/main.cpp \
$$PWD/TetrisBusiness.cpp \
$$PWD/ScoreHistoryModel.cpp \
$$PWD/ScoreHistoryTable.cpp \
$$PWD/Common/DataBase/ITableManage.cpp \
$$PWD/Common/DataBase/SQLiteDatabase.cpp \
$$PWD/Common/DataBase/usersDataTable.cpp
	
RESOURCES += $$PWD/qml.qrc
RC_FILE = $$PWD/Resource.rc

# Additional import path used to resolve QML modules in Qt Creator's code model
QML_IMPORT_PATH =

# Additional import path used to resolve QML modules just for Qt Quick Designer
QML_DESIGNER_IMPORT_PATH =

HEADERS += \
$$PWD/TetrisBusiness.h \
$$PWD/ScoreHistoryModel.h \
$$PWD/ScoreHistoryTable.h \
$$PWD/Common/DataBase/Database_def.h \
$$PWD/Common/DataBase/DatabaseBaseClass.h \
$$PWD/Common/DataBase/DatabaseFactory.h \
$$PWD/Common/DataBase/ITableManage.h \
$$PWD/Common/DataBase/SQLiteDatabase.h \
$$PWD/Common/DataBase/usersDataTable.h


INCLUDEPATH += \
    $$PWD \
    $$PWD/Common/DataBase
